project:
  type: book
  output-dir: docs

book:
  title: "Un acercamiento al Álgebra Lineal"
  author: "LMJD - JEBV"
  date: "01/10/2024"
  chapters:
    - index.qmd
    - 1_introEV.qmd
    - 2_ejemplosEV.qmd
    - 3_subEV.qmd
    - 4_combinacionlineal.qmd
    - 5_espaciogenerado.qmd
    - 6_bases.qmd
    - 7_productointerior.qmd
    - 8_transflineales.qmd
    - 9_modosnormales.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    fontsize: 0.9em
    linestretch: 1.2
    css: styles.css
    crossref:
      eq-prefix: Ecuación     # (default is "Equation")
    code-fold: true
    code-summary: "Mostrar código"
    code-line-numbers: true
    code-copy: true
  pdf:
    documentclass: scrreprt


