project:
  type: book
  output-dir: docs

book:
  title: "Un acercamiento al Álgebra Lineal"
  author: "LMJD - JEBV"
  date: "10/enero/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: moon
  pdf:
    documentclass: scrreprt



